datadog:
  clusterName: my-cluster-1
  #apiKeyExistingSecret: datadog-keys
  apiKey: <datadog-api-key>
  securityAgent:
    compliance:
      enabled: true
      checkInterval: 5m
    runtime:
      enabled: true
      syscallMonitor:
        enabled: true
  expvar_port: 5001
  apm:
    enabled: true
    port: 8126  
    useSocketVolume: false 
    socketPath: /var/run/datadog/apm.socket 
    hostSocketPath: /var/run/datadog/   
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    processCollection: true
  systemProbe:
    enableOOMKill: false
    enableTCPQueueLength: false
    collectDNSStats: true
  networkMonitoring:
    enabled: true
  dogstatsd:
    useHostPort: true
    port: 8125 
    originDetection: false

  env:
    - name: DD_ENV
      value: "lab"
  podSecurity:
    apparmor:
      enabled: false

agents:
  tolerations:
    - operator: Exists
  podAnnotations:
    sidecar.istio.io/inject: "false"
  volumeMounts:
    - mountPath: /etc/datadog-agent/conf.d/istio.d
      name: empty-dir
  volumes:
    - name: empty-dir
      emptyDir: {}
  confd:
    istio.yaml: |-
      ad_identifiers:
        - proxyv2
      init_config:
      instances:
        - istio_mesh_endpoint: http://%%host%%:15090/stats/prometheus
          send_histograms_buckets: true
          send_monotonic_counter: true
clusterAgent:
  admissionController:
    enabled: false
    mutateUnlabelled: false
  env:
    - name: DD_ENV
      value: "lab"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  confd:
    istio.yaml: |-
      ad_identifiers:
        - proxyv2
      init_config:
      instances:
        - istio_mesh_endpoint: http://%%host%%:15090/stats/prometheus
          send_histograms_buckets: true
          send_monotonic_counter: true


